Repository codemuscles/Cowls-Community, pull requests merged in 2022-10, with the labels that each got.

#20 Create InsertionSort.py
  InsertionSort.py
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#19 Create BinarySort.py
  BinarySort.py
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#16 binary codes
  binarySearch.py
  binary_with_rec.py
  binary_without_rec.py
  insertionSort.py
  mergeSort.py
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#26 heap sort
  heapSort.py
Labels: hacktoberfest, hacktoberfest2022

#27 Star pattern
  #pattern.py
  graphics 1.py
Labels: hacktoberfest, hacktoberfest2022

#28 Graphics
  graphics 2.py
Labels: hacktoberfest, hacktoberfest2022

#31 Fibonacii Series in python
  fibonaccifunction.py
Labels: hacktoberfest, hacktoberfest2022

#30 pattern
  Numbers_pattern.py
  Store_water.java
  hanoi.java
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#29 quick sort in python
  quicksort.py
Labels: hacktoberfest, hacktoberfest2022

#33 Age Calculator
  AGE.py
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#32 Electronic Shop Management System
  electronic_shop.java
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#35 created subtract.py
  subtract.py
Labels: hacktoberfest, hacktoberfest2022

#34 Created add.py
  add.py
Labels: hacktoberfest, hacktoberfest2022

#37 userinputadd.py
  userinputadd.py
Labels: hacktoberfest, hacktoberfest2022

#36 onelineadd.py
  onelineadd.py
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#40 Modified Store_water.java code
  Store_water.java
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#39 C Program to find AREA
  area.c
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#45 Add all these
  anagrams.py
  enhanced.jpeg
  flipping images.py
  jumbled game.py
  recurssionbinay.py
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#42 Create LinkedList.c
  LinkedList.c
Labels: hacktoberfest, hacktoberfest2022

#43 JAVA Program to find Volume
  Volume.java
Labels: hacktoberfest2022

#48 add
  addtwonumbers.c
Labels: hacktoberfest, hacktoberfest2022

#50 issupper.c
  isupper.c
Labels: hacktoberfest, hacktoberfest2022

#55 Added index2.html file
  index2.html
Labels: hacktoberfest, hacktoberfest2022, begginerfriendly

#54 Merge sort
  Merge sort.cpp
Labels: hacktoberfest, hacktoberfest2022

#52 Added String Compression 2
  String compression 2.cpp
Labels: hacktoberfest, hacktoberfest2022

#60 Pattern2.c
  c/Pattern2.c
  c/swatika.c
Labels: hacktoberfest, hacktoberfest2022

#58 Create CREATING FLAMES GAME USING PYTHON
  CREATING FLAMES GAME USING PYTHON
Labels: hacktoberfest, hacktoberfest2022

#61 Pattern2.py
  Pattern2.py
Labels: hacktoberfest, hacktoberfest2022

#62 accept mine pr
  Pattern.py
Labels: hacktoberfest, hacktoberfest2022

#63 Hackerrank solutions
  hackerrank/10_Attribute_Parser.cpp
  hackerrank/11_StringStream.cpp
  hackerrank/12_Strings.cpp
  hackerrank/13_Structs.cpp
  hackerrank/14_Class.cpp
  hackerrank/15_Classes_and_Objects.cpp
  hackerrank/16_Box_It.cpp
  hackerrank/17_Inherited_code.cpp
  hackerrank/18_Exceptional_Server.cpp
  hackerrank/19_Virtual_Functions.cpp
  hackerrank/1_Say_HelloWorld_with_CPP.cpp
  hackerrank/20_Abstract_Classes_polymorphism.cpp
  hackerrank/21_Vector_sort.cpp
  hackerrank/22_Vector_Erase.cpp
  hackerrank/23_Lower_Bound_STL.cpp
  hackerrank/24_Sets_STL.cpp
  hackerrank/25_Maps_STL.cpp
  hackerrank/26_Print_Pretty.cpp
  hackerrank/27_Deque_STL.cpp
  hackerrank/28_Inheritance_Introduction.cpp
  hackerrank/29_Hotel_Prices.cpp
  hackerrank/2_Input_and_Output.cpp
  hackerrank/30_Cpp_Exception_Handling.cpp
  hackerrank/31_Rectangle_Area.cpp
  hackerrank/32_Multi_Level_Inheritance.cpp
  hackerrank/33_Overloading_Ostream_Operator.cpp
  hackerrank/34_Messages_Order.cpp
  hackerrank/35_Accessing_Inherited_Functions.cpp
  hackerrank/3_Basic_Data_Types.cpp
  hackerrank/4_Conditional_Statements.cpp
  hackerrank/5_For_Loop.cpp
  hackerrank/6_Functions.cpp
  hackerrank/7_Pointer.cpp
  hackerrank/8_Arrays_Introduction.cpp
  hackerrank/9_Variable_Sized_Arrays.cpp
Labels: hacktoberfest, hacktoberfest2022

#64 linklist code
  linklist.c
Labels: hacktoberfest, hacktoberfest2022

#71 TotalOccurance.cpp
  totalOccurance.cpp
Labels: hacktoberfest, hacktoberfest2022

#70 PeakIndexInMountainArray.cpp
  Peak Index In Mountain Array
Labels: hacktoberfest, hacktoberfest2022

#69 form.html
  form.html
Labels: hacktoberfest, hacktoberfest2022

#68 Rock Scissor paper game
  c/rock_scissor_paper_game.c
Labels: hacktoberfest, hacktoberfest2022

#67 Create count sort.cpp
  cpp/count sort.cpp
Labels: hacktoberfest, hacktoberfest2022

#66 Create maze.py
  python/maze.py
Labels: hacktoberfest, hacktoberfest2022

#65 Searching Algo added pls accept PR .
  java/Searching/BinarySearch.java
  java/Searching/LinearSearch.java
Labels: hacktoberfest, hacktoberfest2022

#92 Create BIRTHDAY PARADOX USING PYTHON
  BIRTHDAY PARADOX USING PYTHON
Labels: hacktoberfest, hacktoberfest2022

#91 Create JUMBLE WORDS USING PYTHON
  JUMBLE WORDS USING PYTHON
Labels: hacktoberfest, hacktoberfest2022

#72 Reverse Array uploaded PR
  java/MergeSort.java
  java/ReverseArray.java
Labels: hacktoberfest, hacktoberfest2022

#84 Create LOTTERY SIMULATION
  LOTTERY SIMULATION
Labels: hacktoberfest, hacktoberfest2022

#88 Create ROCK PAPER SCISSOR GAME USING PYTHON
  ROCK PAPER SCISSOR GAME USING PYTHON
Labels: hacktoberfest, hacktoberfest2022

#82 sinxfunctioninc++.cpp
  sin(x).cpp
Labels: hacktoberfest, hacktoberfest2022

#78 Asteroid game in C++
  Asteroid.c.cpp
Labels: hacktoberfest, hacktoberfest2022

#83 Image steganography
  Image Steganography.py
Labels: hacktoberfest, hacktoberfest2022

#75 Bucket Sort.cpp
  cpp/Bucket Sort.cpp
Labels: hacktoberfest, hacktoberfest2022

#76 Create Tower of Hanoi (iterative).cpp
  cpp/Tower of Hanoi (iterative).cpp
Labels: hacktoberfest, hacktoberfest2022

#77 Create pascal star pattern.js
  pascal star pattern.js
Labels: hacktoberfest, hacktoberfest2022

#90 Create MAGIC SQUARE USING PYTHON.
  MAGIC SQUARE USING PYTHON.
Labels: hacktoberfest, hacktoberfest2022

#89 Create DOUBLE GAME USING PYTHON
  DOUBLE GAME USING PYTHON
Labels: hacktoberfest, hacktoberfest2022

#79 knapsack algo and jswd
  python/job_sequencing_with_deadlines.py
  python/knapsack_algorithm.py
Labels: hacktoberfest, hacktoberfest2022

#80 amend
  cpp/linear search.cpp
Labels: hacktoberfest, hacktoberfest2022

#85 Create SPIRAL TRAVERSING
  SPIRAL TRAVERSING
Labels: hacktoberfest, hacktoberfest2022

#86 Create TIC TAC TOE GAME USING PYTHON
  TIC TAC TOE GAME USING PYTHON
Labels: hacktoberfest, hacktoberfest2022

#87 Create MONTE HALL GAME USING PYTHON
  MONTE HALL GAME USING PYTHON
Labels: hacktoberfest, hacktoberfest2022
